name: "hire-thec"
services: 
  flask:
    build: flask
    ports:
      - "8000:8000"
    volumes:
      - ./flask:/flask_app
    env_file:
      - .env
    depends_on:
    - db
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  db:
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
      #hello_flask_dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
volumes:
  postgres_data: